
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ELearningManagement - fontend-fservice
  name: front
spec:
  ports:
  - port: 80
  selector:
    service: ELearningManagement - fontend-frontend
  type: LoadBalancer